language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
    - downloads
python:
  - 2.7
matrix:
  fast_finish: true
install:
  - python bootstrap-buildout.py
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - bin/coverage run bin/test
after_success:
  - bin/coveralls

notifications:
  email:
    - itconsense@gmail.com
